DATA_FILE_PATH = './Data/data.json'

INVOICE_DIRECTORY_PATH = './Invoices'
#INVOICE_DIRECTORY_PATH = 'Z:/Kuba/Invoices'

ARCHIVE_DIRECTORY = 'Archive'
INVOICE_XML_DIRECTORY = 'Invoice_XML'
INVOICE_PDF_DIRECTORY = 'Invoice_PDF'
OLD_ARCHIVE_DIRECTORY = 'Old_Archive'

OUTPUT_DIRECTORY_PATH = './Faktury'